mysqldata:
  image: mysql:latest
  volumes:
    - /var/lib/mysql
  command: true

mysql:
  image: mysql:latest
  volumes_from:
    - mysqldata
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: mysql

tomcatdata:
  image: tomcat:7
  volumes:
    - /usr/local/tomcat
  command: true

jasperdata:
  image: tomcat:7
  volumes:
    - /jasperconfig
  command: true

jasperserver:
  build: .
  volumes_from:
    - tomcatdata
    - jasperdata
  ports:
    - "8080:8080"
  links:
    - mysql:database
